name: stock-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.0.3
  - matplotlib=3.10.1
  - plotly=6.1.2
  - flask=3.1.1
  - dash=3.0.4
  - dash-bootstrap-components=2.0.3
  - gunicorn=23.0.0
  - openpyxl=3.0.9
  - ipython=8.37.0
  - pytest=7.4.3
  - pyyaml=6.0
  - requests=2.32.4
  - lxml=4.8.0
  - ta-lib=0.4.19
  - certifi=2025.4.26
  - openssl=3.0.16
  - libffi=3.4.4
  - pip:
    - finlab==1.3.0
    - shioaji==1.2.5
    - google.genai==1.59.0
    - google-auth-oauthlib==1.2.4
    - google-auth-httplib2==0.3.0
    - google-api-python-client==2.188.0
    - pydantic==2.11.6
    - pydantic-core==2.33.2
    - python-dotenv
    - python-telegram-bot
    - pytz==2025.2
    - loguru==0.6.0
    - tqdm==4.67.1
    - websocket-client==1.8.0
    - msgpack==1.1.1
    - orjson==3.10.18
    - cython==3.1.2
    - cryptography==45.0.4
    - base58==2.1.1
    - based58==0.1.1
    - cffi==1.17.1
    - ciso8601==2.3.2
    - filelock==3.4.1
    - flask-autoindex==0.6.6
    - fugle-trade==1.2.0
    - fugle-trade-core==2.1.0
    - keyring==23.5.0
    - keyrings-cryptfile==1.3.8
    - lz4==4.4.4
    - markupsafe==3.0.2
    - parso==0.8.4
    - pyarrow==20.0.0
    - pycryptodome==3.23.0
    - pynacl==1.5.0
    - pyrsca==0.1.2
    - pysolace==0.9.40
    - python-dateutil==2.9.0.post0
    - sentry-sdk==1.5.12
    - six==1.17.0
    - typing-inspection==0.4.1
    - xxhash==3.5.0
    - annotated-types==0.7.0
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==21.2.0
