name: stock-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - numpy=1.26.4
  - flask=3.1.1
  - dash=3.0.4
  - dash-bootstrap-components=2.0.3
  - gunicorn=23.0.0
  - plotly=6.1.2
  - ta-lib
  - openpyxl
  - lxml
  - pip
  - pip:
      - finlab==1.3.0
      - shioaji==1.2.5
      - fugle-trade==1.2.0
      - google.genai==1.59.0
      - pydantic==2.11.6
      - python-dotenv
      - loguru==0.6.0
      - tqdm
      - PyYAML
      - google-api-python-client==2.188.0
      - google-auth-oauthlib==1.2.4
      - google-auth-httplib2==0.3.0
      - google.genai==1.59.0
      - flask-autoindex==0.6.6
      - keyring==23.5.0